<?php

namespace AppBundle\Repository;

/**
 * BlogTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogTagRepository extends \Doctrine\ORM\EntityRepository
{
}
